on:
  workflow_call:
    inputs:
      year:
        required: false
        type: number
      artifact-input-filename:
        required: true
        type: string
      artifact-input-path:
        required: true
        type: string
      artifact-output-filename:
        required: true
        type: string
      artifact-output-path:
        required: true
        type: string

jobs:
  md_to_epub:
    name: Markdown to PDF
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y pandoc texlive-xetex fonts-ubuntu

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-input-filename }}
          path: ${{ inputs.artifact-input-path }}

      - name: Convert Markdown to ePub
        run: ./scripts/md2pdf.sh -o=${{ inputs.artifact-output-filename }} -y=${{ inputs.year }}

      - name: Upload ePub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-output-filename }}
          path: ${{ inputs.artifact-output-path }}
          retention-days: 7