on:
  workflow_call:
    inputs:
      year:
        required: true
        type: number
      run-checks:
        required: false
        type: boolean
        default: false

jobs:
  create_book:
    name: Create books for ${{ inputs.year }}
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y language-pack-ru
      - run: sudo dpkg-reconfigure locales

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        if: ${{ inputs.run-checks }}
        run: pytest

      - run: python3 book/src/main.py -y ${{ inputs.year }}

#      - name: Compress Markdown
#        run: zip markdown-${{ inputs.year }}.zip ./output_data/markdown/*

      - name: Upload Markdown
        uses: actions/upload-artifact@v4
        with:
#          name: markdown-${{ inputs.year }}.zip
#          path: markdown-${{ inputs.year }}.zip
          name: markdown-${{ inputs.year }}
          path: output_data/markdown/
          compression-level: 9
          if-no-files-found: error
          retention-days: 7

  convert_md_to_pdf:
    name: Markdown to PDF
    uses: ./.github/workflows/lib-pdf.yml
    needs: [ create_book ]
    with:
      year: ${{ inputs.year }}
      artifact-input-filename: markdown-${{ inputs.year }}.zip
      artifact-input-path: '.'
      artifact-output-filename: liturgical-calendar-${{ inputs.year }}.pdf
      artifact-output-path: ./output_data/pdf/liturgical-calendar-${{ inputs.year }}.pdf

  convert_md_to_epub:
    name: Markdown to ePub
    uses: ./.github/workflows/lib-epub.yml
    needs: [ create_book ]
    with:
      year: ${{ inputs.year }}
      artifact-input-filename: markdown-${{ inputs.year }}.zip
      artifact-input-path: '.'
      artifact-output-filename: liturgical-calendar-${{ inputs.year }}.epub
      artifact-output-path: ./output_data/epub/liturgical-calendar-${{ inputs.year }}.epub

  convert_md_to_fb2:
    name: Markdown to fb2
    uses: ./.github/workflows/lib-fb2.yml
    needs: [ create_book ]
    with:
      year: ${{ inputs.year }}
      artifact-input-filename: markdown-${{ inputs.year }}.zip
      artifact-input-path: '.'
      artifact-output-filename: liturgical-calendar-${{ inputs.year }}.fb2
      artifact-output-path: ./output_data/fb2/liturgical-calendar-${{ inputs.year }}.fb2

  convert_epub_to_azw:
    name: ePub to AZW
    uses: ./.github/workflows/lib-azw.yml
    needs: [ convert_md_to_epub ]
    with:
      artifact-input-filename: liturgical-calendar-${{ inputs.year }}.epub
      artifact-input-path: ./output_data/epub/
      artifact-output-filename: liturgical-calendar-${{ inputs.year }}.azw3
      artifact-output-path: ./output_data/azw/liturgical-calendar-${{ inputs.year }}.azw3
