name: ePub to AZW

on:
  workflow_call:
    inputs:
      artifact-input-filename:
        required: true
        type: string
      artifact-input-path:
        required: true
        type: string

jobs:
  epub_to_azw3:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libegl1 libopengl0 libxcb-cursor0
      - name: Install Calibre
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-input-filename }}
          path: ${{ inputs.artifact-input-path }}
      - name: Convert ePub to AZW3
        run: ./scripts/epub2azw.sh
      - name: Upload AZW
        uses: actions/upload-artifact@v3
        with:
          name: liturgical-calendar.azw3
          path: ./output_data/azw/liturgical-calendar.azw3
          retention-days: 7
