name: CI

on:
  push:
    branches: [ main ]

jobs:
  create_book_current:

    strategy:
      matrix:
        year: [2024]

    name: Book ${{ matrix.year }}
    uses: ./.github/workflows/lib-book.yml
    with:
      year: ${{ matrix.year }}
      run-checks: true
