name: CI

on:
  push:
    branches: [ main ]

jobs:
  create_book:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y pandoc texlive-xetex language-pack-ru fonts-ubuntu
      - run: sudo dpkg-reconfigure locales
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 main.py
      - run: ./scripts/md2epub.sh
      - run: ./scripts/md2pdf.sh
      - name: Upload ePub
        uses: actions/upload-artifact@v3
        with:
          name: liturgical-calendar.epub
          path: ./output_data/epub/liturgical-calendar.epub
          retention-days: 7
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: liturgical-calendar.pdf
          path: ./output_data/pdf/liturgical-calendar.pdf
          retention-days: 7

  convert_epub_to_azw:
    name: ePub to AZW
    uses: ./.github/workflows/lib-calibre.yml
    needs: [ create_book ]
    with:
      artifact-input-filename: liturgical-calendar.epub
      artifact-input-path: ./output_data/epub/
      artifact-output-filename: liturgical-calendar.azw3
      artifact-output-path: ./output_data/azw/liturgical-calendar.azw3
