name: CI

on:
  push:
    branches: [ main ]

jobs:
  create_book:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y language-pack-ru
      - run: sudo dpkg-reconfigure locales
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 main.py

      - name: Compress Markdown
        run: zip markdown.zip ./output_data/markdown/*

      - name: Upload Markdown
        uses: actions/upload-artifact@v3
        with:
          name: markdown.zip
          path: '.'
          retention-days: 7

  convert_md_to_pdf:
    name: Markdown to PDF
    uses: ./.github/workflows/lib-pdf.yml
    needs: [ create_book ]
    with:
      artifact-input-filename: markdown.zip
      artifact-input-path: '.'
      artifact-output-filename: liturgical-calendar.pdf
      artifact-output-path: ./output_data/pdf/liturgical-calendar.pdf

  convert_md_to_epub:
    name: Markdown to ePub
    uses: ./.github/workflows/lib-epub.yml
    needs: [ create_book ]
    with:
      artifact-input-filename: markdown.zip
      artifact-input-path: '.'
      artifact-output-filename: liturgical-calendar.epub
      artifact-output-path: ./output_data/epub/liturgical-calendar.epub

  convert_epub_to_azw:
    name: ePub to AZW
    uses: ./.github/workflows/lib-calibre.yml
    needs: [ convert_md_to_epub ]
    with:
      artifact-input-filename: liturgical-calendar.epub
      artifact-input-path: ./output_data/epub/
      artifact-output-filename: liturgical-calendar.azw3
      artifact-output-path: ./output_data/azw/liturgical-calendar.azw3
